//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::author::Entity as Author;
pub use super::source::Entity as Source;
pub use super::source_author_mapping::Entity as SourceAuthorMapping;
pub use super::source_tag_mapping::Entity as SourceTagMapping;
pub use super::tag::Entity as Tag;
